# Generated by Django 4.0.4 on 2022-07-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=24)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
                ('contact', models.PositiveIntegerField()),
                ('foodallergens', models.CharField(choices=[('Milk', 'Milk'), ('Egg', 'Egg'), ('Fish', 'Fish'), ('Shellfish', 'Shellfish'), ('Tree nuts', 'Tree nuts'), ('Peanuts', 'Peanuts'), ('Wheat', 'Wheat'), ('Soybeans', 'Soybeans')], max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Quantity', models.PositiveIntegerField()),
                ('Order_Date', models.DateField()),
                ('Customer_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(choices=[('Nutrigeek Juice', 'Nutrigeek Juice'), ('Nutrigeek Coffee', 'Nutrigeek Coffee'), ('Nutrigeek Vitamins', 'Nutrigeek Vitamins')], max_length=24)),
                ('Product_Name', models.CharField(blank=True, max_length=24)),
                ('Product_Description', models.TextField(blank=True)),
                ('Product_Price', models.PositiveIntegerField()),
                ('Product_Quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Category', models.CharField(choices=[('Nutrigeek Juice', 'Nutrigeek Juice'), ('Nutrigeek Coffee', 'Nutrigeek Coffee'), ('Nutrigeek Vitamins', 'Nutrigeek Vitamins')], max_length=24)),
                ('Payment_Date', models.DateField()),
                ('Payment_Type', models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Gcash', 'Gcash'), ('Paymaya', 'Paymaya'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit Card')], max_length=24)),
                ('Payment_Amount', models.PositiveIntegerField()),
                ('Customer_Payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.customer')),
                ('Order_Payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Product_Reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.product'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_Courier', models.CharField(choices=[('J&T', 'J&T'), ('Flash', 'Flash'), ('Toktok', 'Toktok'), ('JRS Express', 'JRS Express'), ('Ninja Van', 'Ninja Van')], max_length=24)),
                ('Arrival_Date', models.DateField()),
                ('Customer_Delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.customer')),
                ('Order_Delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.order')),
            ],
        ),
    ]
